import type { Metadata } from "next";
import { Be_Vietnam_Pro, Space_Mono } from "next/font/google";
import "./globals.css";
import TikTokChecker from "@/components/TikTokChecker";
import DebugUaBadge from "./debug-ua/debuguabadge";

const sansFont = Be_Vietnam_Pro({
  weight: ["400", "500", "600", "700"],
  variable: "--font-sans",
  subsets: ["vietnamese", "latin"],
});

const monoFont = Space_Mono({
  weight: ["400", "700"],
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title:
    "Audio Không Quảng Cáo - Nghe audio mọi thể loại hay nhất cập nhật mỗi ngày",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <>
      <html
        lang="en"
        className={`${sansFont.variable} ${monoFont.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <TikTokChecker />
          {children}
          {/* TAM THOI de debug UA tren dien thoai - XOA dong nay sau khi xong */}
          <DebugUaBadge />
        </body>
      </html>
    </>
  );
}
